version: '4'

services:
  postgres:
    image: docker.io/library/pg_test:0.5
      # image: guoqiangqi/postgresql-vector-search:v17
    container_name: pg_test
      # container_name: postgresql_with_extensions
    environment:
      POSTGRES_USER: nju_common
      POSTGRES_PASSWORD: opensource
      POSTGRES_DB: compass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nju_common -d compass"]
      interval: 5s
      timeout: 5s
      retries: 5
        # command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/ssd/postgresql-data
      o: bind
